edition = "2024"
reorder_imports = true

comment_width = 120
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Item"
wrap_comments = true

normalize_comments = true
newline_style = "Unix"
merge_derives = false
format_macro_matchers = true
