[package]
name = "x"
publish = false
edition.workspace = true

[package.metadata.release]
release = false

[dependencies]
clap.workspace = true
which = { version = "8.0.0" }

[lints]
workspace = true
