[package]
name = "x"
publish = false
edition.workspace = true

[package.metadata.release]
release = false

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
which = { version = "8.0.0" }

[lints]
workspace = true
