[package]
name = "emos_tmdb_api"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
dotenv_codegen = { workspace = true }
emos_utils.workspace = true

[dev-dependencies]
tokio = { workspace = true }
